# Generated by Django 5.0.6 on 2024-06-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body3",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
