# Generated by Django 5.0.6 on 2024-06-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_message_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(default="...پیام خود را وارد کنید ...", null=True),
        ),
    ]
