# Generated by Django 5.0.6 on 2024-06-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description2",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
